SCREEN_WIDTH, SCREEN_HEIGHT = 1600, 900
TITLE = "Room 3"

PLAYER_SCALING = 0.6
PLAYER_MOVEMENT_SPEED = 7
PLAYER_JUMP_SPEED = 17
GRAVITY = 1
PLAYER_MAX_HP = 100

CAMERA_LERP = 0.12
DEAD_ZONE_W = int(SCREEN_WIDTH * 0.35 / 3)
DEAD_ZONE_H = int(SCREEN_HEIGHT * 0.45 / 3)

DASH_SPEED = 40
DASH_DURATION = 0.2
DASH_COOLDOWN = 1.0

GEYSER_DAMAGE = 30
GEYSER_ACTIVE_DURATION = 1.5
GEYSER_COOLDOWN_DURATION = 3.0
GEYSER_WIDTH = 100
GEYSER_HEIGHT = 65
GEYSER_BLAST_SPEED = 15